### PR TITLE
fix first example; use https for all repl.it links

### PR DESCRIPTION
**Pull request by ryanpcmcquen**

### CODE REVIEW

**Comment by nelsonic** [comment]
Well spotted!
Thanks for fixing this @ryanpcmcquen :+1:

**Comment by ryanpcmcquen** [comment]
Wow, you merge quickly! Glad to help. :wink:

**Comment by nelsonic** [comment]
@ryanpcmcquen I'm a _notifications addict_ ... :bell: 
and when I see a good addition it makes sense not to keep people waiting... :wink: 
Please :star: the repo to help spread the word (_if you think it will be useful to anyone else_...)

**Comment by ryanpcmcquen** [comment]
Thanks, and done! :tada:

**Pull request merged**
